apiVersion: v1
kind: Namespace
metadata:
  name: soas
  labels:
    # Istio sidecar injection — every pod in this namespace gets
    # the envoy sidecar that handles mTLS.
    istio-injection: enabled
    name: soas
