apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: soas
resources:
  - peerauthentication.yaml
  - destinationrule.yaml
  - requestauthentication.yaml
  - authorizationpolicy.yaml
  - gateway-user.yaml
  - gateway-webhook.yaml
  - virtualservice-user.yaml
  - virtualservice-webhook.yaml
