// MCP tool registry for the SOAS backend.
//
// Tools are grouped by domain (incidents, automations, wiki, RAG, etc.) and exposed via
// `registerTools(server, client)`. Each tool returns a stringified JSON payload back to
// the MCP client — that's the SDK's expected content shape.
//
// A few design choices worth noting:
//   * Errors from the API are surfaced as "isError: true" content blocks. This keeps
//     Claude reasoning about failures explicitly instead of hallucinating success.
//   * Schemas use zod with descriptions so that tool documentation is auto-generated by
//     the MCP SDK at handshake time.
//   * For destructive operations (deletes, automation runs) we include a sanity-style
//     description telling the model what the side-effect is — Claude tends to read those.

import { z } from "zod";
import { SoasApiError } from "./soas-client.js";

const STRING = z.string();
const UUID_DESC = "UUID string";

const SeverityEnum = z.enum(["critical", "high", "medium", "low", "informational"]);
const AutomationStatus = z.enum(["draft", "active", "disabled", "archived"]);

function ok(data) {
  return {
    content: [
      {
        type: "text",
        text: typeof data === "string" ? data : JSON.stringify(data, null, 2),
      },
    ],
  };
}

function failure(err) {
  let body;
  if (err instanceof SoasApiError) {
    body = { error: err.message, status: err.status, detail: err.body };
  } else {
    body = { error: String(err && err.message ? err.message : err) };
  }
  return {
    isError: true,
    content: [{ type: "text", text: JSON.stringify(body, null, 2) }],
  };
}

function wrap(handler) {
  return async (args) => {
    try {
      return ok(await handler(args));
    } catch (err) {
      return failure(err);
    }
  };
}

export function registerTools(server, client) {
  // ─── Health & meta ─────────────────────────────────────────────────────
  server.tool(
    "soas_health",
    "Check that the SOAS backend, embeddings service, and worker are reachable.",
    {},
    wrap(async () => {
      const backend = await client.get("/../health").catch(() => null) ?? await client.get("/../../api/health");
      let ragStatus = null;
      try {
        ragStatus = await client.get("/rag/status");
      } catch {
        ragStatus = { status: "unavailable" };
      }
      return { backend, rag: ragStatus };
    }),
  );

  // ─── Incidents ─────────────────────────────────────────────────────────
  server.tool(
    "soas_list_incidents",
    "List incidents with optional filters. Returns a paginated response.",
    {
      severity: SeverityEnum.optional(),
      status: STRING.optional().describe("Free-form status filter (open, closed, ...)"),
      assignee_id: STRING.optional().describe(UUID_DESC),
      page: z.number().int().min(1).default(1),
      per_page: z.number().int().min(1).max(100).default(25),
    },
    wrap((args) => client.get("/incidents", args)),
  );

  server.tool(
    "soas_get_incident",
    "Fetch an incident by ID, including its timeline.",
    { incidentId: STRING.describe(UUID_DESC) },
    wrap(async ({ incidentId }) => {
      const [incident, timeline] = await Promise.all([
        client.get(`/incidents/${incidentId}`),
        client.get(`/incidents/${incidentId}/timeline`).catch(() => null),
      ]);
      return { incident, timeline };
    }),
  );

  server.tool(
    "soas_create_incident",
    "Create a new incident. Use a short, descriptive title.",
    {
      title: STRING.min(1).max(500),
      severity: SeverityEnum,
      summary: STRING.optional(),
      tags: z.array(STRING).optional(),
      assignee_id: STRING.optional().describe(UUID_DESC),
    },
    wrap((args) => client.post("/incidents", args)),
  );

  server.tool(
    "soas_update_incident",
    "Update fields on an existing incident.",
    {
      incidentId: STRING.describe(UUID_DESC),
      patch: z
        .record(z.any())
        .describe("Object of fields to update (title, severity, status, summary, tags, assignee_id, ...)"),
    },
    wrap(({ incidentId, patch }) => client.patch(`/incidents/${incidentId}`, patch)),
  );

  server.tool(
    "soas_delete_incident",
    "Delete an incident. This is destructive and cannot be undone.",
    { incidentId: STRING.describe(UUID_DESC) },
    wrap(({ incidentId }) => client.del(`/incidents/${incidentId}`)),
  );

  server.tool(
    "soas_list_incident_notes",
    "List notes on an incident.",
    { incidentId: STRING.describe(UUID_DESC) },
    wrap(({ incidentId }) => client.get(`/incidents/${incidentId}/notes`)),
  );

  server.tool(
    "soas_add_incident_note",
    "Add a note to an incident.",
    {
      incidentId: STRING.describe(UUID_DESC),
      content: STRING.min(1),
    },
    wrap(({ incidentId, content }) =>
      client.post(`/incidents/${incidentId}/notes`, { content }),
    ),
  );

  // ─── Cases ─────────────────────────────────────────────────────────────
  server.tool(
    "soas_list_cases",
    "List cases.",
    {
      status: STRING.optional(),
      page: z.number().int().min(1).default(1),
      per_page: z.number().int().min(1).max(100).default(25),
    },
    wrap((args) => client.get("/cases", args)),
  );

  server.tool(
    "soas_get_case",
    "Fetch a case by ID.",
    { caseId: STRING.describe(UUID_DESC) },
    wrap(({ caseId }) => client.get(`/cases/${caseId}`)),
  );

  server.tool(
    "soas_create_case",
    "Create a new case.",
    {
      title: STRING.min(1).max(500),
      summary: STRING.optional(),
      severity: SeverityEnum.optional(),
    },
    wrap((args) => client.post("/cases", args)),
  );

  server.tool(
    "soas_update_case",
    "Update an existing case.",
    {
      caseId: STRING.describe(UUID_DESC),
      patch: z.record(z.any()),
    },
    wrap(({ caseId, patch }) => client.patch(`/cases/${caseId}`, patch)),
  );

  server.tool(
    "soas_link_case_incident",
    "Link an incident to a case.",
    {
      caseId: STRING.describe(UUID_DESC),
      incidentId: STRING.describe(UUID_DESC),
    },
    wrap(({ caseId, incidentId }) =>
      client.post(`/cases/${caseId}/incidents`, { incident_id: incidentId }),
    ),
  );

  // ─── Automations ───────────────────────────────────────────────────────
  server.tool(
    "soas_list_automations",
    "List automations.",
    {
      status: AutomationStatus.optional(),
      page: z.number().int().min(1).default(1),
      per_page: z.number().int().min(1).max(100).default(25),
    },
    wrap((args) => client.get("/automations", args)),
  );

  server.tool(
    "soas_get_automation",
    "Fetch an automation by ID, including its graph_data.",
    { automationId: STRING.describe(UUID_DESC) },
    wrap(({ automationId }) => client.get(`/automations/${automationId}`)),
  );

  server.tool(
    "soas_create_automation",
    "Create a new automation. graph_data is the VP2 JSON shape.",
    {
      name: STRING.min(1).max(500),
      description: STRING.optional(),
      graph_data: z.record(z.any()).optional(),
      status: AutomationStatus.default("draft"),
    },
    wrap((args) => client.post("/automations", args)),
  );

  server.tool(
    "soas_update_automation",
    "Update fields on an existing automation. Pass graph_data to replace the visual graph.",
    {
      automationId: STRING.describe(UUID_DESC),
      patch: z.record(z.any()),
    },
    wrap(({ automationId, patch }) =>
      client.patch(`/automations/${automationId}`, patch),
    ),
  );

  server.tool(
    "soas_delete_automation",
    "Delete an automation. Destructive.",
    { automationId: STRING.describe(UUID_DESC) },
    wrap(({ automationId }) => client.del(`/automations/${automationId}`)),
  );

  server.tool(
    "soas_run_automation",
    "Execute an automation. Returns the execution_id which can be polled with soas_get_execution.",
    {
      automationId: STRING.describe(UUID_DESC),
      parameters: z.record(z.any()).optional(),
      incident_id: STRING.optional().describe(UUID_DESC),
    },
    wrap(({ automationId, parameters, incident_id }) =>
      client.post(`/automations/${automationId}/execute`, {
        parameters: parameters || {},
        incident_id,
      }),
    ),
  );

  server.tool(
    "soas_get_execution",
    "Fetch an execution log by ID.",
    { executionId: STRING.describe(UUID_DESC) },
    wrap(({ executionId }) => client.get(`/executions/${executionId}`)),
  );

  server.tool(
    "soas_list_executions",
    "List recent executions.",
    {
      automation_id: STRING.optional().describe(UUID_DESC),
      status: STRING.optional(),
      page: z.number().int().min(1).default(1),
      per_page: z.number().int().min(1).max(100).default(25),
    },
    wrap((args) => client.get("/executions", args)),
  );

  server.tool(
    "soas_get_node_catalog",
    "Return the catalog of available graph node types (categories, inputs, outputs, properties).",
    {},
    wrap(() => client.get("/graph-editor/node-catalog")),
  );

  // ─── Wiki CRUD ────────────────────────────────────────────────────────
  server.tool(
    "soas_list_wiki_pages",
    "List wiki pages with optional search/filter.",
    {
      search: STRING.optional(),
      tag: STRING.optional(),
      parent_id: STRING.optional().describe(UUID_DESC),
      root: z.boolean().optional().describe("Only root-level pages"),
      page: z.number().int().min(1).default(1),
      per_page: z.number().int().min(1).max(100).default(50),
    },
    wrap((args) => client.get("/wiki", args)),
  );

  server.tool(
    "soas_get_wiki_tree",
    "Return the full wiki page tree for navigation.",
    {},
    wrap(() => client.get("/wiki/tree")),
  );

  server.tool(
    "soas_get_wiki_page",
    "Get a wiki page by ID.",
    { pageId: STRING.describe(UUID_DESC) },
    wrap(({ pageId }) => client.get(`/wiki/${pageId}`)),
  );

  server.tool(
    "soas_get_wiki_page_by_slug",
    "Get a wiki page by URL slug.",
    { slug: STRING },
    wrap(({ slug }) => client.get(`/wiki/by-slug/${slug}`)),
  );

  server.tool(
    "soas_create_wiki_page",
    "Create a new wiki page.",
    {
      title: STRING.min(1),
      content: STRING.optional(),
      slug: STRING.optional(),
      parent_id: STRING.optional().describe(UUID_DESC),
      tags: z.array(STRING).optional(),
      icon: STRING.optional(),
    },
    wrap((args) => client.post("/wiki", args)),
  );

  server.tool(
    "soas_update_wiki_page",
    "Update a wiki page's title, content, tags, or status.",
    {
      pageId: STRING.describe(UUID_DESC),
      patch: z.record(z.any()),
    },
    wrap(({ pageId, patch }) => client.patch(`/wiki/${pageId}`, patch)),
  );

  server.tool(
    "soas_delete_wiki_page",
    "Delete a wiki page. Destructive.",
    { pageId: STRING.describe(UUID_DESC) },
    wrap(({ pageId }) => client.del(`/wiki/${pageId}`)),
  );

  server.tool(
    "soas_search_wiki_fulltext",
    "Full-text search the wiki using PostgreSQL tsvector. Cheap and exact, no embeddings.",
    {
      q: STRING.min(1),
      page: z.number().int().min(1).default(1),
      per_page: z.number().int().min(1).max(100).default(20),
    },
    wrap((args) => client.get("/wiki/search", args)),
  );

  // ─── Wiki RAG (semantic) ──────────────────────────────────────────────
  server.tool(
    "soas_rag_wiki_search",
    "Semantic search over the wiki using local embeddings. Use this when the user's question is conceptual or paraphrases topics that may not match keyword search.",
    {
      q: STRING.min(1).describe("Natural-language query"),
      top_k: z.number().int().min(1).max(50).default(5),
      min_score: z.number().min(-1).max(1).default(0.0),
    },
    wrap((args) => client.get("/rag/search", args)),
  );

  server.tool(
    "soas_rag_status",
    "Index health: how many wiki pages are indexed, embedding service status, model info.",
    {},
    wrap(() => client.get("/rag/status")),
  );

  server.tool(
    "soas_rag_reindex_all",
    "Schedule a full re-index of every wiki page. Admin only. Returns immediately; indexing happens in the worker.",
    {},
    wrap(() => client.post("/rag/reindex")),
  );

  server.tool(
    "soas_rag_reindex_page",
    "Re-index a single wiki page now.",
    { pageId: STRING.describe(UUID_DESC) },
    wrap(({ pageId }) => client.post(`/rag/reindex/${pageId}`)),
  );

  // ─── Variables, secrets, teams ────────────────────────────────────────
  server.tool(
    "soas_list_soas_variables",
    "List SOAS-wide variables.",
    {},
    wrap(() => client.get("/soas-variables")),
  );

  server.tool(
    "soas_list_incident_variables",
    "List incident-scoped variable definitions.",
    {},
    wrap(() => client.get("/incident-variables")),
  );

  server.tool(
    "soas_list_teams",
    "List teams.",
    {},
    wrap(() => client.get("/teams")),
  );

  server.tool(
    "soas_get_team",
    "Get a team by ID.",
    { teamId: STRING.describe(UUID_DESC) },
    wrap(({ teamId }) => client.get(`/teams/${teamId}`)),
  );

  server.tool(
    "soas_list_team_variables",
    "List variables scoped to a team.",
    { teamId: STRING.describe(UUID_DESC) },
    wrap(({ teamId }) => client.get(`/teams/${teamId}/variables`)),
  );

  server.tool(
    "soas_list_users",
    "List users (admin only).",
    {
      page: z.number().int().min(1).default(1),
      per_page: z.number().int().min(1).max(100).default(50),
    },
    wrap((args) => client.get("/users", args)),
  );

  server.tool(
    "soas_list_roles",
    "List roles + their assigned permissions.",
    {},
    wrap(() => client.get("/roles")),
  );

  // ─── Webhooks & sources ───────────────────────────────────────────────
  server.tool(
    "soas_list_webhooks",
    "List ingest webhooks.",
    {
      page: z.number().int().min(1).default(1),
      per_page: z.number().int().min(1).max(100).default(50),
    },
    wrap((args) => client.get("/webhooks", args)),
  );

  server.tool(
    "soas_get_webhook",
    "Fetch a webhook by ID.",
    { webhookId: STRING.describe(UUID_DESC) },
    wrap(({ webhookId }) => client.get(`/webhooks/${webhookId}`)),
  );

  server.tool(
    "soas_list_webhook_sources",
    "List webhook sources (CrowdStrike, Splunk, etc.) with linked automations.",
    {},
    wrap(() => client.get("/webhook-sources")),
  );

  // ─── Issues ──────────────────────────────────────────────────────────
  server.tool(
    "soas_list_issues",
    "List bug/feature issues.",
    {
      status: STRING.optional(),
      page: z.number().int().min(1).default(1),
      per_page: z.number().int().min(1).max(100).default(50),
    },
    wrap((args) => client.get("/issues", args)),
  );

  server.tool(
    "soas_create_issue",
    "Create an issue.",
    {
      title: STRING.min(1),
      description: STRING.optional(),
      severity: STRING.optional(),
    },
    wrap((args) => client.post("/issues", args)),
  );

  // ─── Generic raw access (escape hatch) ────────────────────────────────
  server.tool(
    "soas_api_get",
    "Issue an arbitrary GET against the SOAS API. Use only when no specialized tool covers the endpoint. Path must start with `/`.",
    {
      path: STRING.regex(/^\//, "Path must start with /"),
      query: z.record(z.any()).optional(),
    },
    wrap(({ path, query }) => client.get(path, query)),
  );

  server.tool(
    "soas_api_post",
    "Issue an arbitrary POST against the SOAS API. Read soas_api_get's caveats first.",
    {
      path: STRING.regex(/^\//),
      body: z.record(z.any()).optional(),
    },
    wrap(({ path, body }) => client.post(path, body || {})),
  );

  server.tool(
    "soas_api_patch",
    "Issue an arbitrary PATCH against the SOAS API.",
    {
      path: STRING.regex(/^\//),
      body: z.record(z.any()),
    },
    wrap(({ path, body }) => client.patch(path, body)),
  );

  server.tool(
    "soas_api_delete",
    "Issue an arbitrary DELETE against the SOAS API.",
    { path: STRING.regex(/^\//) },
    wrap(({ path }) => client.del(path)),
  );

  // ─── Embeddings (raw) ─────────────────────────────────────────────────
  server.tool(
    "soas_embed_texts",
    "Embed arbitrary text(s) using the local sentence-transformers model. Useful for ad-hoc similarity / clustering / dedup.",
    {
      texts: z.array(STRING).min(1).max(64),
      normalize: z.boolean().default(true),
    },
    wrap(({ texts, normalize }) => client.embed(texts, { normalize })),
  );
}
